-- CREATE TABLE IF NOT EXISTS projects(
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     name text NOT NULL CHECK (name <> ''),
--     priority integer NOT NULL,
--     description text,
--     deliverydate date NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS tasks(
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     name text NOT NULL CHECK (name <> ''),
--     done BOOLEAN,
--     projectId INTEGER REFERENCES projects(id)
-- );

CREATE TABLE IF NOT EXISTS projects(
    id SERIAL PRIMARY KEY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id SERIAL PRIMARY KEY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

-- INSERT PROJECTS DATA
INSERT INTO projects(name, priority, description, deliverydate) VALUES('Make a Web App', 1,'Using Javascript', '2020-09-10');
INSERT INTO projects(name, priority, description, deliverydate) VALUES('Make a App', 1,'Using Dart', '2020-09-24');
INSERT INTO projects(name, priority, description, deliverydate) VALUES('Make a Desktop App', 2,'Using C++', '2020-09-28');

-- INSERT TASKS DATA
INSERT INTO tasks(name, done, projectId) VALUES('Download Vuejs',false,1);
INSERT INTO tasks(name, done, projectId) VALUES('Create UI WEB',false,1);
INSERT INTO tasks(name, done, projectId) VALUES('Download Flutter',false,2);
INSERT INTO tasks(name, done, projectId) VALUES('Design UI',false,2);